import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserratSans = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={montserratSans.className}>{children}</body>
		</html>
	)
}
